import { useEffect, useState } from 'react';
import { getSkillResults, getHealthTrend } from '../services/api';
import type { SkillResults, HealthTrend } from '../types';

export default function AdminPage() {
  const [skillResults, setSkillResults] = useState<SkillResults | null>(null);
  const [healthTrend, setHealthTrend] = useState<HealthTrend | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  useEffect(() => {
    const fetchData = async () => {
      try {
        const [skillResp, trendResp] = await Promise.all([
          getSkillResults(),
          getHealthTrend(),
        ]);
        setSkillResults(skillResp.data);
        setHealthTrend(trendResp.data);
      } catch {
        setError('Failed to load admin data.');
      } finally {
        setLoading(false);
      }
    };
    fetchData();
  }, []);

  if (loading) return <div className="p-4">Loading...</div>;
  if (error) return <div className="p-4 text-red-600">{error}</div>;

  return (
    <div className="max-w-4xl mx-auto p-4">
      <h1 className="text-2xl font-bold mb-6">Admin Console</h1>

      {/* Health Trend */}
      <section className="mb-8">
        <h2 className="text-xl font-semibold mb-3">Health Trend</h2>
        {healthTrend && (
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-4">
            <div className="bg-blue-50 rounded-lg p-4">
              <p className="text-sm text-blue-600">Overall Average</p>
              <p className="text-2xl font-bold text-blue-800">{healthTrend.overall_average}/5</p>
            </div>
            <div className="bg-green-50 rounded-lg p-4">
              <p className="text-sm text-green-600">Meals Logged</p>
              <p className="text-2xl font-bold text-green-800">{healthTrend.total_logs}</p>
            </div>
            <div className="bg-purple-50 rounded-lg p-4">
              <p className="text-sm text-purple-600">Adherence</p>
              <p className="text-2xl font-bold text-purple-800">{healthTrend.adherence_percent}%</p>
            </div>
          </div>
        )}

        {healthTrend && healthTrend.weekly_scores.length > 0 && (
          <div className="border rounded-lg p-4">
            <h3 className="font-medium mb-2">Weekly Autoimmune Scores</h3>
            <div className="space-y-2">
              {healthTrend.weekly_scores.map((ws) => (
                <div key={ws.week} className="flex items-center gap-3">
                  <span className="text-sm text-gray-500 w-20">{ws.week}</span>
                  <div className="flex-1 bg-gray-200 rounded-full h-4">
                    <div className="bg-indigo-500 h-4 rounded-full" style={{ width: `${(ws.average / 5) * 100}%` }} />
                  </div>
                  <span className="text-sm font-medium w-16">{ws.average}/5 ({ws.count})</span>
                </div>
              ))}
            </div>
          </div>
        )}

        {healthTrend && healthTrend.weekly_scores.length === 0 && (
          <p className="text-gray-500">No dish logs yet. Start logging meals to see your health trend.</p>
        )}
      </section>

      {/* Skill Results */}
      <section className="mb-8">
        <h2 className="text-xl font-semibold mb-3">Skill Analysis Results</h2>
        <p className="text-sm text-gray-500 mb-4">
          These are generated by running Claude Code skills. Run them from the CLI to update.
        </p>

        <div className="space-y-4">
          <SkillCard title="User Preferences" data={skillResults?.user_preferences ?? null} description="Taste profile from recipe-analyzer skill" />
          <SkillCard title="User Memory" data={skillResults?.user_memory ?? null} description="Behavior patterns from user-profile-builder skill" />
          <SkillCard title="Recommendation Weights" data={skillResults?.recommendation_weights ?? null} description="Scoring weights from meal-plan-optimizer skill" />
        </div>
      </section>
    </div>
  );
}

function SkillCard({ title, data, description }: { title: string; data: Record<string, unknown> | null; description: string }) {
  const [expanded, setExpanded] = useState(false);

  return (
    <div className="border rounded-lg p-4">
      <div className="flex justify-between items-start">
        <div>
          <h3 className="font-medium">{title}</h3>
          <p className="text-sm text-gray-500">{description}</p>
        </div>
        {data ? (
          <span className="text-xs bg-green-100 text-green-800 px-2 py-1 rounded">
            Last run: {(data as Record<string, unknown>).generated_at as string || 'unknown'}
          </span>
        ) : (
          <span className="text-xs bg-gray-100 text-gray-600 px-2 py-1 rounded">Not yet run</span>
        )}
      </div>
      {data && (
        <>
          <button onClick={() => setExpanded(!expanded)} className="text-sm text-indigo-600 mt-2 hover:underline">
            {expanded ? 'Hide details' : 'Show details'}
          </button>
          {expanded && (
            <pre className="mt-2 bg-gray-50 rounded p-3 text-xs overflow-auto max-h-64">
              {JSON.stringify(data, null, 2)}
            </pre>
          )}
        </>
      )}
    </div>
  );
}
